# Isi panduan BAA.flow — bahasa sederhana. Label tombol ditulis persis seperti di aplikasi.
# notes: satu teks per penanda (urutan sama dengan daftar penanda di shots.cjs); None = penanda tidak dipakai.

ADMIN = {
 'id': 'admin', 'role': 'Admin', 'icon': 'shield_person',
 'lead': 'Admin menyiapkan project, membuat akun tim, memantau progres, dan menjaga data tetap rapi.',
 'flow': [('add_circle', 'Buat project'), ('tune', 'Siapkan (Setup)'), ('rocket_launch', 'Activate'), ('monitoring', 'Pantau & bantu tim'), ('ac_unit', 'Freeze bila perlu')],
 'topics': [
  {'id': 'a-start', 'title': 'Pertama kali membuka aplikasi',
   'lead': 'Saat aplikasi baru dipasang, admin login dengan akun bawaan lalu langsung diminta mengganti password.',
   'shot': 'a_firstpw',
   'notes': ['Ketik password baru (minimal 4 karakter).', 'Ketik ulang password yang sama.', 'Klik **Save & continue**.'],
   'warn': ['Password bawaan (admin / admin) diketahui umum. Aplikasi tidak bisa dipakai sebelum diganti.']},
  {'id': 'a-first-project', 'title': 'Buat project pertama',
   'lead': 'Satu project = satu pekerjaan BAA dengan template, data, dan tim sendiri.',
   'shot': 'a_firstproject',
   'notes': ['Nama project, mis. *Kopdes Merah Putih*.', 'Awalan kode lokasi (2–4 huruf). Kode lokasi pertama jadi mis. **LOK_00001**.', 'Warna project — membantu membedakan project di layar.', 'Klik **Create & start setup**.'],
   'tips': ['Project baru selalu mulai kosong dan berstatus **Setup**. Belum ada yang bisa mengisi BAA sampai project diaktifkan.']},
  {'id': 'a-layout', 'title': 'Kenali layar utama',
   'lead': 'Semua menu ada di sidebar kiri. Bagian bawah sidebar selalu terlihat.',
   'shot': 'a_layout',
   'notes': ['**Pemilih project** — pindah project (atau tekan Ctrl+K).', '**Portfolio** — ringkasan semua project.', '**BAA Entry** — tempat mengisi BAA per lokasi.', '**Location Log** — daftar semua lokasi, impor, dan export.', '**Settings** — pengaturan project ini dan workspace.', '**Lonceng** — permintaan edit dari operator.', 'Timer kerja hari ini.', 'Ganti tema terang / gelap.']},
  {'id': 'a-setup', 'title': 'Siapkan project (mode Setup)',
   'lead': 'Selama Setup, sidebar berubah menjadi langkah-langkah. Kerjakan dari atas ke bawah, lalu aktifkan.',
   'flow': [('list_alt', 'Location data'), ('description', 'Template BAA'), ('group_add', 'Team'), ('event', 'Target (opsional)'), ('rocket_launch', 'Activate')],
   'shot': 'a_setup_overview',
   'notes': ['Langkah setup. Tanda ✓ = selesai, ! = wajib belum selesai.', '**Location data** — field, kategori foto, inventory.', '**Template BAA** — file Excel BAA + pemetaan sel.', '**Team** — siapa saja yang boleh masuk.', '**Target** — boleh diisi nanti.', '**Activate project** aktif setelah semua langkah wajib selesai.'],
   'tips': ['Isi Location data dulu sebelum Template — pemetaan template memerlukan field dan kategori foto.']},
  {'id': 'a-fields', 'title': 'Location data · Field lokasi',
   'lead': 'Tentukan data apa saja yang wajib diisi teknisi untuk setiap lokasi.',
   'shot': 'a_setup_fields',
   'notes': ['Tiga tab: **Location fields**, **Photos**, **Inventory**. Angka = jumlah isian.', 'Setiap baris = satu field. *Nama Lokasi* adalah field sistem (terkunci).', '**Quick add** — tambah field umum dengan sekali klik.', '**+ Field** — buat field sendiri.', 'Simpan perubahan.', 'Tombol **Back / Next** untuk pindah langkah.'],
   'tips': ['Nyalakan **Required** untuk field yang wajib diisi. Pilih **Date** untuk tanggal.']},
  {'id': 'a-photos', 'title': 'Location data · Kategori foto',
   'lead': 'Setiap kategori = satu kotak foto di BAA Entry dan satu gambar di BAA.',
   'shot': 'a_setup_photos',
   'notes': ['Tab **Photos**.', 'Daftar kategori: nama, kata kunci nama file, OCR nomor seri.', '**+ Category** untuk menambah.'],
   'tips': ['**Kata kunci**: foto yang nama filenya mengandung kata ini otomatis masuk kategori tersebut saat upload banyak foto.', 'Nyalakan **OCR** untuk foto label SN agar nomor seri terbaca otomatis.']},
  {'id': 'a-inventory', 'title': 'Location data · Inventory',
   'lead': 'Barang yang dipasang di lokasi (mis. Kit Starlink, Router, Access Point).',
   'shot': 'a_setup_inventory',
   'notes': ['Tab **Inventory**.', None, 'Pilihan **Notes** (mis. "OK") yang muncul sebagai dropdown di BAA Entry.'],
   'tips': ['Isi **Default items** agar baris inventory langsung terisi nama barang pada lokasi baru.']},
  {'id': 'a-team', 'title': 'Team · Buat akun & beri akses',
   'lead': 'Buat akun operator langsung dari sini. Akun baru otomatis mendapat akses ke project ini.',
   'shot': 'a_setup_team',
   'notes': ['Isi nama lengkap, username, dan pilih peran (**Operator** atau **Viewer**).', 'Klik **Add**.', 'Password sementara muncul di sini — klik **Copy** lalu kirim ke orangnya.', 'Nyalakan / matikan akses akun lain ke project ini.'],
   'tips': ['Operator wajib mengganti password sementara saat login pertama.']},
  {'id': 'a-target', 'title': 'Target (opsional)',
   'lead': 'Jumlah BAA yang harus selesai dan tenggat waktunya. Dipakai untuk menghitung kecepatan di Dashboard dan Progress.',
   'shot': 'a_setup_target',
   'notes': ['Jumlah BAA.', 'Tanggal target.', '**Save target**.']},
  {'id': 'a-template', 'title': 'Template BAA',
   'lead': 'Unggah file Excel BAA, lalu petakan kolom dan sel agar data otomatis masuk saat export.',
   'flow': [('upload_file', 'Upload template'), ('table_rows', 'Petakan Log Sheet'), ('grid_on', 'Petakan Detail Sheet'), ('save', 'Save mapping')],
   'shot': 'a_template',
   'notes': ['Template yang sedang aktif.', '**Upload template** — pilih file .xlsx.', 'Langkah 1: pilih template & sheet.', 'Langkah 2: **Log Sheet** — tabel daftar lokasi.', 'Langkah 3: **Detail Sheet** — halaman BAA per lokasi (data, inventory, foto).', '**Save mapping** setelah selesai.']},
  {'id': 'a-template-map', 'title': 'Template BAA · Memetakan kolom',
   'lead': 'Untuk setiap judul kolom di Excel, pilih data aplikasi yang akan mengisinya.',
   'shot': 'a_template_map',
   'notes': ['Langkah yang sedang dibuka.', 'Pilih isi kolom dari daftar (Data, Wilayah, Inventory, Foto).', 'Persentase pemetaan yang sudah lengkap.', '**Save mapping**.'],
   'tips': ['Lupa menyimpan? Saat pindah menu, aplikasi akan bertanya **Save / Discard**.']},
  {'id': 'a-dash', 'title': 'Dashboard admin',
   'lead': 'Ringkasan harian: capaian tim, kecepatan, dan siapa yang perlu dibantu.',
   'shot': 'a_dash',
   'notes': ['Info cepat (mis. jumlah lokasi yang menunggu diselesaikan).', 'Capaian vs target, kecepatan yang dibutuhkan, dan tanggal target.', 'Tabel tim: online/tidak, draf terbuka, umur draf.', None]},
  {'id': 'a-progress', 'title': 'Progress & peta wilayah',
   'lead': 'Lihat sebaran lokasi per wilayah dan prakiraan capaian target.',
   'shot': 'a_progress',
   'notes': ['Peta per kabupaten/kota — klik baris untuk memperbesar.', None],
   'tips': ['Klik ikon pensil di angka target / tanggal untuk mengubahnya langsung.']},
  {'id': 'a-portfolio', 'title': 'Portfolio (banyak project)',
   'lead': 'Satu kartu per project. Klik kartu untuk membuka project itu.',
   'shot': 'a_portfolio',
   'notes': ['Total semua project.', 'Kartu project: persentase, status kecepatan, draf terbuka.', 'Peta mini sebaran lokasi.']},
  {'id': 'a-log', 'title': 'Location Log',
   'lead': 'Daftar semua lokasi. Cari, saring, export, impor, dan pulihkan lokasi yang terhapus.',
   'shot': 'a_log',
   'notes': ['**Active / Deleted** — lihat lokasi yang terhapus dan pulihkan.', '**Import locations** dari Excel.', 'Cari kode atau nama lokasi.', 'Saring berdasarkan pembuat.', 'Saring berdasarkan wilayah.', 'Export banyak lokasi sekaligus (Excel / PDF per lokasi).', 'Centang beberapa lokasi untuk aksi massal (mis. isi wilayah).'],
   'tips': ['Klik baris lokasi untuk membuka panel detail di kanan.']},
  {'id': 'a-drawer', 'title': 'Panel detail lokasi',
   'lead': 'Cek kelengkapan satu lokasi tanpa membuka BAA Entry.',
   'shot': 'a_drawer',
   'notes': ['Persentase kelengkapan lokasi.', 'Foto yang sudah ada (klik untuk melihat di BAA Entry).', 'Status **Scan PDF** — klik **Open** untuk membuka.', 'Perangkat terpasang dan nomor serinya.', '**Edit in BAA Entry**.']},
  {'id': 'a-import', 'title': 'Import lokasi dari Excel',
   'lead': 'Masukkan banyak lokasi sekaligus. Kode lokasi dibuat otomatis.',
   'flow': [('download', 'Download template'), ('edit_note', 'Isi di Excel'), ('upload_file', 'Upload'), ('preview', 'Cek preview'), ('done_all', 'Import')],
   'shot': 'a_import',
   'notes': ['Ikuti 4 langkah di kiri.', '**Download Template** — format Excel yang benar.', 'Klik untuk memilih file yang sudah diisi.', 'Klik **Import** setelah preview benar.']},
  {'id': 'a-notif', 'title': 'Permintaan edit (lonceng)',
   'lead': 'Operator hanya bisa mengubah lokasi miliknya. Jika perlu mengubah lokasi orang lain, ia mengirim permintaan.',
   'shot': 'a_notif',
   'notes': ['Lokasi, peminta, dan pemilik saat ini.', '**Approve** — lokasi pindah ke peminta.', None, 'Angka merah di lonceng = jumlah permintaan baru.'],
   'tips': ['Tombol **✕** untuk menolak permintaan.']},
  {'id': 'a-trash', 'title': 'Lokasi terhapus',
   'lead': 'Lokasi yang dihapus tidak langsung hilang. Data dan foto tetap tersimpan.',
   'shot': 'a_trash',
   'notes': ['Tab **Deleted** di Location Log.', 'Pulihkan atau hapus permanen dari sini.']},
  {'id': 'a-status', 'title': 'Project & status',
   'lead': 'Ubah nama, warna, target, fitur Wilayah, dan akses. Di sini juga Freeze / Unfreeze.',
   'shot': 'a_status',
   'notes': ['Status project: **SETUP**, **ACTIVE**, atau **FROZEN**.', '**Freeze** — hentikan semua input sementara.', 'Awalan kode terkunci setelah kode pertama terbit.', 'Target BAA dan tanggal.', 'Fitur **Wilayah data** dan apakah dihitung dalam kelengkapan.', 'Siapa saja yang punya akses.'],
   'tips': ['Ada perubahan yang belum disimpan? Indikator **Unsaved** muncul di kanan atas dan aplikasi mengingatkan sebelum pindah menu.']},
  {'id': 'a-freeze', 'title': 'Freeze project',
   'lead': 'Bekukan project saat admin perlu merapikan sesuatu (mis. revisi template). Operator hanya bisa melihat.',
   'shot': 'a_freeze',
   'notes': ['Tulis pesan untuk tim.', 'Atau pilih pesan cepat.', 'Pratinjau banner yang dilihat tim.', '**Freeze project**.'],
   'warn': ['Saat Frozen, operator tidak bisa mengisi, mengubah, upload, impor, maupun export.']},
  {'id': 'a-frozen', 'title': 'Saat project Frozen',
   'lead': 'Admin tetap bisa mengubah pengaturan dan data. Banner biru muncul di semua halaman.',
   'shot': 'a_frozen',
   'notes': ['Banner pesan untuk semua user.', 'Status **FROZEN**.', '**Edit message** — ubah pesan.', '**Unfreeze** — buka kembali input.', '**Change prefix…** — ganti awalan kode (hanya saat Frozen).']},
  {'id': 'a-recode', 'title': 'Ganti awalan kode lokasi',
   'lead': 'Mengubah semua kode, mis. LOK_00001 → KMP_00001. Nomor tetap sama; folder foto & scan ikut pindah.',
   'shot': 'a_recode',
   'notes': ['Ketik awalan baru, klik **Analyse**.', 'Ringkasan yang akan berubah.', 'Contoh kode lama → baru.', None, '**Re-code** untuk menerapkan.'],
   'tips': ['Kode lama tetap bisa dicari di Location Log.'],
   'warn': ['File PDF/Excel yang sudah pernah dikirim tetap memakai kode lama.']},
  {'id': 'a-users', 'title': 'Users',
   'lead': 'Kelola semua akun di seluruh project.',
   'shot': 'a_user_dlg',
   'notes': ['Username untuk login.', 'Peran: **Operator** (isi BAA), **Viewer** (lihat saja), **Admin**.', 'Project yang boleh dibuka.', '**Save**.'],
   'tips': ['Mengisi password baru untuk user lama = reset password. User wajib menggantinya saat login berikutnya.']},
  {'id': 'a-backup', 'title': 'Backup & Restore',
   'lead': 'Simpan cadangan seluruh data secara rutin.',
   'shot': 'a_backup',
   'notes': ['**Download backup** — satu file berisi semua data & foto.', None, 'Pulihkan dari file backup.'],
   'warn': ['Restore mengganti seluruh data saat ini dengan isi file backup.']},
 ],
 'cheat': [
  ('Mulai project baru', 'Settings › All projects › **New project** → kerjakan langkah Setup → **Activate project**'),
  ('Tambah operator', 'Settings › This project › **Team** → isi nama & username → **Add** → kirim password sementara'),
  ('Ubah template / mapping', 'Settings › **Template BAA** → **Save mapping**'),
  ('Pantau tim', '**Dashboard** (harian) · **Progress** (peta & target) · **Portfolio** (semua project)'),
  ('Permintaan edit', 'Ikon **lonceng** → **Approve** / ✕'),
  ('Hentikan input sementara', 'Project & status › **Freeze** → tulis pesan → nanti **Unfreeze**'),
  ('Export banyak lokasi', '**Location Log** → saring → **Excel (template)** / **PDF per location (ZIP)**'),
  ('Cadangkan data', 'Settings › **Backup & Restore** → **Download**'),
 ],
}

OPERATOR = {
 'id': 'operator', 'role': 'Operator', 'icon': 'engineering',
 'lead': 'Operator mengisi BAA per lokasi: data, wilayah, inventory, foto, dan scan PDF, lalu menyimpannya sampai lengkap.',
 'flow': [('add_location_alt', 'Lokasi baru'), ('edit_note', 'Isi data & wilayah'), ('inventory_2', 'Inventory'), ('photo_camera', 'Foto'), ('picture_as_pdf', 'Scan PDF'), ('task_alt', 'Save BAA')],
 'topics': [
  {'id': 'o-start', 'title': 'Login pertama',
   'lead': 'Admin memberi username dan password sementara. Saat login pertama, ganti dengan password sendiri.',
   'shot': 'o_firstpw',
   'notes': ['Password baru (minimal 4 karakter).', 'Ulangi password baru.', '**Save & continue**.'],
   'tips': ['Lupa password? Minta admin membuat password sementara baru.']},
  {'id': 'o-dash', 'title': 'Dashboard saya',
   'lead': 'Lihat target minggu ini dan draf yang perlu diselesaikan.',
   'shot': 'o_dash',
   'notes': ['**New location** — mulai BAA baru.', '**Continue** — lanjutkan draf yang paling hampir selesai.', 'Target pribadi minggu ini.', 'Draf saya: persentase, yang masih kurang, dan umur draf. Klik **Open**.'],
   'tips': ['Chip kuning/oranye menunjukkan apa yang masih kurang, mis. *Scan PDF* atau *2 photos*.']},
  {'id': 'o-entry', 'title': 'BAA Entry · Data lokasi',
   'lead': 'Satu halaman untuk satu lokasi. Ringkasan di kanan menunjukkan apa yang masih kurang.',
   'shot': 'o_entry',
   'notes': ['Pilih lokasi yang mau diisi.', '**Add Location** — buat lokasi baru (kode dibuat otomatis).', 'Isi data lokasi. Tanda * = wajib.', 'Wilayah: desa, kecamatan, kab/kota, provinsi.', '**BAA Summary** — persentase dan daftar kekurangan.', '**Save BAA** — simpan.']},
  {'id': 'o-wil', 'title': 'Mengisi wilayah dengan cepat',
   'lead': 'Ketik nama desa ditambah kata lain (kecamatan / kabupaten) — urutan bebas, boleh salah ketik sedikit.',
   'shot': 'o_wilayah',
   'notes': ['Ketik mis. *cibodas lembang*.', 'Pilih hasil yang benar — keempat tingkat terisi sekaligus.', 'Desa tidak ada di daftar? Isi manual sesuai tulisan teknisi.']},
  {'id': 'o-inv', 'title': 'Inventory',
   'lead': 'Perangkat yang dipasang: jenis, jumlah, nomor seri (SN), dan keterangan.',
   'shot': 'o_inventory',
   'notes': [None, None, 'Isi setiap baris. SN bisa terisi otomatis dari foto label (OCR).'],
   'tips': ['Brand/Type dan Notes punya pilihan yang muncul saat mengetik.']},
  {'id': 'o-photo', 'title': 'Foto',
   'lead': 'Seret banyak foto sekaligus — aplikasi memasukkan ke kategori yang cocok berdasarkan nama file.',
   'shot': 'o_photos',
   'notes': ['**Upload** — pilih banyak foto sekaligus (atau seret ke area ini).', '**Clear all** — hapus semua foto lokasi ini.', 'Jumlah kategori yang sudah terisi.', 'Kotak per kategori. Klik kotak untuk mengganti, mengedit, atau mengisi SN manual.'],
   'tips': ['Beri nama file sesuai kategori (mis. *depan.jpg*, *sn_router.jpg*) agar otomatis masuk kotak yang benar.']},
  {'id': 'o-scan', 'title': 'Scan PDF',
   'lead': 'Dokumen BAA bertanda tangan yang sudah discan. Wajib untuk setiap lokasi.',
   'shot': 'o_scan',
   'notes': ['Klik atau seret file .pdf ke sini (maks. 25 MB).', 'Label **Required** berubah hijau setelah diupload.'],
   'tips': ['Scan PDF menjadi halaman pertama saat export PDF.']},
  {'id': 'o-save', 'title': 'Simpan & selesai',
   'lead': 'Lokasi otomatis berstatus **Done** saat data, inventory, dan foto lengkap lalu disimpan.',
   'shot': 'o_summary',
   'notes': ['Persentase kelengkapan.', 'Baris hijau = sudah lengkap.', 'Baris merah = masih kurang.', '**Save BAA**.', 'Export **PDF** lokasi ini.', 'Export **Excel** lokasi ini.'],
   'tips': ['Lupa menyimpan? Saat pindah lokasi atau menu, aplikasi akan bertanya **Save / Discard**.']},
  {'id': 'o-log', 'title': 'Location Log',
   'lead': 'Daftar semua lokasi. Semua orang bisa melihat semua lokasi.',
   'shot': 'o_log',
   'notes': ['Cari kode atau nama.', 'Saring **All / Draft / Done**.', 'Klik baris untuk membuka panel detail.', 'Export banyak lokasi sekaligus.']},
  {'id': 'o-drawer', 'title': 'Lengkapi dari panel detail',
   'lead': 'Upload foto yang kurang dan scan PDF langsung dari panel, tanpa membuka BAA Entry.',
   'shot': 'o_drawer',
   'notes': ['Kotak putus-putus = foto yang belum ada.', 'Klik kotak → pilih foto → **Save**.', 'Scan PDF: klik **Upload**.', '**Edit in BAA Entry** untuk mengubah yang lain.']},
  {'id': 'o-request', 'title': 'Lokasi milik orang lain',
   'lead': 'Lokasi orang lain hanya bisa dilihat (**Read Only**). Untuk mengubahnya, minta akses ke admin.',
   'shot': 'o_request',
   'notes': ['Tanda **Read Only**.', '**Request edit** — setelah admin menyetujui, lokasi pindah menjadi milik Anda.']},
  {'id': 'o-export', 'title': 'Export',
   'lead': 'Buat file Excel BAA atau PDF untuk dikirim.',
   'shot': 'o_export',
   'notes': ['Lokasi sesuai saringan yang sedang aktif.', 'Atau semua lokasi.', '**Create** — file disiapkan lalu diunduh.']},
  {'id': 'o-frozen', 'title': 'Saat project dibekukan (Frozen)',
   'lead': 'Admin sedang merapikan sesuatu. Anda tetap bisa melihat data, tetapi belum bisa mengisi atau mengubah.',
   'shot': 'o_frozen_entry',
   'notes': ['Pesan dari admin dan sejak kapan dibekukan.'],
   'tips': ['Tunggu sampai admin membuka kembali (Unfreeze). Data yang sudah tersimpan aman.']},
 ],
 'cheat': [
  ('Mulai BAA baru', 'Dashboard › **New location** atau BAA Entry › **Add Location**'),
  ('Lanjutkan draf', 'Dashboard › **Continue** / **Open** di daftar *My drafts*'),
  ('Isi wilayah', 'Ketik *desa + kecamatan/kabupaten* → pilih hasil'),
  ('Upload banyak foto', 'Bagian Photos › **Upload** atau seret file'),
  ('Lengkapi cepat', 'Location Log › klik lokasi → kotak putus-putus / **Upload** scan'),
  ('Selesai', '**Save BAA** — status Done otomatis bila lengkap'),
  ('Ubah lokasi orang lain', 'Panel detail › **Request edit**'),
  ('Kirim file', '**PDF** / **Excel** di BAA Summary atau export di Location Log'),
 ],
}

STATUS = [
 ('SETUP', 'Project sedang disiapkan admin. Belum bisa diisi.', 'setup'),
 ('ACTIVE', 'Normal — tim bisa mengisi BAA.', 'active'),
 ('FROZEN', 'Dibekukan sementara — hanya bisa dilihat.', 'frozen'),
 ('DRAFT', 'Lokasi belum lengkap.', 'draft'),
 ('DONE', 'Lokasi lengkap & tersimpan.', 'done'),
]
